# fly.toml app configuration file generated for tracks-lat on 2023-11-14T16:04:14-03:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tracks-lat"
primary_region = "yul"

[build]

[http_service]
internal_port = 80
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
